-- DROP TABLES IF EXISTS
DROP TABLE IF EXISTS GR04_Comentario CASCADE;
DROP TABLE IF EXISTS GR04_CostoDepto CASCADE;
DROP TABLE IF EXISTS GR04_Departamento CASCADE;
DROP TABLE IF EXISTS GR04_EstadoLuegoOcupacion CASCADE;
DROP TABLE IF EXISTS GR04_Habitacion CASCADE;
DROP TABLE IF EXISTS GR04_Huesped CASCADE;
DROP TABLE IF EXISTS GR04_Huesped_Reserva CASCADE;
DROP TABLE IF EXISTS GR04_Pago CASCADE;
DROP TABLE IF EXISTS GR04_Persona CASCADE;
DROP TABLE IF EXISTS GR04_Reserva CASCADE;
DROP TABLE IF EXISTS GR04_Tipo_Dpto CASCADE;
DROP TABLE IF EXISTS GR04_Tipo_Pago CASCADE;

--DROP FUNCTIONS
DROP FUNCTION IF EXISTS TRFN_GR04_Control_Cant_Habitaciones_Departamento() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR04_Control_Dueño_No_Reserva() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR04_Control_Huesped_Dueño_No_Reserva() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR04_No_Superar_Cant_Huespedes() CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR04_Disponibilidad_Dpto(date) CASCADE;
DROP FUNCTION IF EXISTS TRFN_GR04_Disponibilidad_Dpto_En_Rango_Fechas(fecha1 date,fecha2 date,city varchar(50)) CASCADE;

-- DROP VIEWS
DROP VIEW IF EXISTS GR04_Departamentos_Recaudacion_Ultimos_6_Meses CASCADE; 
DROP VIEW IF EXISTS GR04_Listado_Ciudad_Por_Nombre_Y_Rating CASCADE;